config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root :to =>"homes#top"
    get '/about' => 'homes#about'
    get "/mypage" => "users#mypage"
    resources :users, except: [:new, :index, :create] do
      collection do
        patch :withdraw
        get :check
      end
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resources :group_users, only: [:show, :create, :destroy]
      resources :group_characters
      resources :messages, only: [:create, :destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :rooms, only: [:create, :index, :show] do
      resources :direct_messages, only: [:create, :destroy]
    end
    # mount ActionCable.server => '/cable'
    resources :characters
    resources :schedules, except: [:index]
    resources :notifications, only: [:update]
    get "/search", to: "searches#search"
  end

  devise_scope :user do
    get '/users/sign_out', to: 'public/sessions#destroy'
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    # resources :groups, only: [:show, :index, :destroy]
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_user, only: [:destroy]
      resources :group_characters, only: [:show, :destroy]
      resources :messages, only: [:destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    resources :characters, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    get "/search", to: "searches#search"
  end

  devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :content, presence: true, length: { maximum: 300 }
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController

  def create
    # メッセージをする対象の投稿(group)のインスタンスを作成
    @group = Group.find(params[:group_id])
    #投稿に紐づいたメッセージを作成
    @message = @group.messages.new(message_params)
    # メッセージ投稿者(user)のidを代入
    @message.user_id = current_user.id
    @message.score = Language.get_data(message_params[:content])  #この行を追加
    if @message.save
      flash.now[:notice] = "メッセージの投稿に成功しました。"
    else
      flash.now[:alert] ="メッセージの投稿に失敗しました。"
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:id])
    @message.destroy
    flash.now[:notice] = "メッセージを削除しました。"
  end

  private
    def message_params
      params.require(:message).permit(:content, :user_id, :group_id)
    end
end

app/views/admin/messages/_count.html.erb
<div class="d-flex justify-content-between">
  <h5>メッセージ</h5>
  <h5>メッセージ（<%= messages.reject{ |message| message.user.is_deleted? }.count %>件)</h5>
</div>

app/views/admin/messages/_current.html.erb
<div class="message" id="<%= message.id %>">
  <div class="posted-chat-frame">
    <div class="posted-chat-content">
      <span><b><%= "#{message.user.name}" %></b></span>&nbsp;&nbsp;<small><%= message.created_at.strftime("%Y/%m/%d %H:%M") %></small>
      <p><%= "#{message.content}" %>
        <button data-id="<%= message.id %>" class="delete-btn btn btn-danger" data-confirm="メッセージを削除しますか？">削除</button>
      </p>
    </div>
  </div>
</div>

app/views/admin/messages/_index.html.erb
<hr>
<% group.messages.each do |message| %>
  <% if message.user && message.user.is_deleted? %>
    <% next %>
  <% end %>
  <div class="d-flex" style="padding-bottom: 16px;">
    <div class="profile-img-frame">
      <%= image_tag message.user.get_image, size:'60x60', class: "icon-img" %>
    </div>
    <div class="posted-chat-content" style="padding-left: 10px;">
      <span><b><%= message.user.name %></b></span>&nbsp;&nbsp;<small><%= message.created_at.strftime("%Y/%m/%d %H:%M") %></small>
      <!-- メッセージの表示 -->
      <p><%= safe_join(message.content.split("\n"),tag(:br))%></p>
      <p class="sentiment-score">本文の感情分析スコア[<%= message.score %>]</p>
    </div>
    <div style="text-align: right; margin-left: auto;">
      <%= link_to admin_group_message_path(message.group_id, message.id), method: :delete, remote: true do %>
        <button class="btn btn-outline-secondary" style="padding:0rem 0.4rem 0.2rem 0.5rem; border-radius: 20vh;">×</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/messages/_other.html.erb
<div class="message" id="<%= message.id %>">
  <div class="posted-chat-frame">
    <div class="posted-chat-content">
      <span><b><%= "#{message.user.name}" %></b></span>&nbsp;&nbsp;<small><%= message.created_at.strftime("%Y/%m/%d %H:%M") %></small>
      <p><%= "#{message.content}" %>
    </div>
  </div>
</div>

app/views/admin/messages/create.js.erb
$('#message_index').html('<%= j(render "admin/messages/index", group: @message.group) %>');
$('#message_count').html('<%= j(render "admin/messages/count", messages: @group.messages) %>')

app/views/admin/messages/destroy.js.erb
$('#message_index').html('<%= j(render "admin/messages/index", group: @message.group) %>');
$('#message_count').html('<%= j(render "admin/messages/count", messages: @group.messages) %>')