config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root :to =>"homes#top"
    get '/about' => 'homes#about'
    get "/mypage" => "users#mypage"
    resources :users, except: [:new, :index, :create] do
      collection do
        patch :withdraw
        get :check
      end
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resources :group_users, only: [:show, :create, :destroy]
      resources :group_characters
      resources :messages, only: [:create, :destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :rooms, only: [:create, :index, :show] do
      resources :direct_messages, only: [:create, :destroy]
    end
    # mount ActionCable.server => '/cable'
    resources :characters
    resources :schedules, except: [:index]
    resources :notifications, only: [:update]
    get "/search", to: "searches#search"
  end

  devise_scope :user do
    get '/users/sign_out', to: 'public/sessions#destroy'
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    # resources :groups, only: [:show, :index, :destroy]
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_user, only: [:destroy]
      resources :group_characters, only: [:show, :destroy]
      resources :messages, only: [:destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    resources :characters, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    get "/search", to: "searches#search"
  end

  devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users,      dependent: :destroy
  has_many :permits,          dependent: :destroy
  has_many :users,            through: :group_users, source: :user
  has_many :messages,         dependent: :destroy
  has_many :group_characters, dependent: :destroy
  has_many :characters,       through: :group_characters
  has_many :schedules
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  has_one_attached :image

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "partial"
      return Group.where("title LIKE ?", "%#{word}%")
    end
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController

  def index
    @group = Group.new
    @groups = Group.all
    @group_lists = Group.all.order(:id)
  end

  def show
    @group = Group.find(params[:id])
    @messages = @group.messages
    @message = Message.new
    @character_lists = @group.characters
  end

  def edit
    @group = Group.find(params[:id])
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    redirect_to admin_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/index.html.erb
<h4 style="padding-left: 10px;">グループ一覧</h4>
<br>
<table class="table table-bordered">
  <tr class="table-active">
    <th width="60"><br></th>
    <th>グループ名</th>
    <th colspan="2">参加人数</th>
  </tr>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td>
          <%= link_to admin_group_path(group.id) do %>
            <%= image_tag group.get_image, size: '60x60', class: "icon-img" %>
          <% end %>
        </td>
        <td style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 0;">
          <%= link_to group.title, admin_group_path(group.id), class: "group-link" %>
        </td>
        <td width="70">
          <i class="fa-solid fa-users"></i><%= group.users.select { |user| user.user_status == "有効" }.count %>
        </td>
        <td width="90">
          <%= link_to '削除', admin_group_path(group), method: :delete, data: { confirm: '本当にグループを削除しますか?' },class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/groups/show.html.erb
<div class="sidebars">
  <div class="sidebar is-closed">
    <button class="sidebar-toggle is-closed"><i class="fa fa-plus icon"></i></button>
    <%= render 'admin/group_users/index', group: @group %>
    <%= render 'admin/group_characters/index', group: @group, character_lists: @character_lists %>
    <%= link_to 'グループを削除', admin_group_path(@group), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %>
  </div>
</div>

<div class="messages" style="padding-right: 1rem; padding-left: 1rem;">
  <div class="d-flex justify-content-between">
    <div class="d-flex" style="margin-top: 4px;">
      <%= image_tag @group.get_image, size: '100x100', class: "icon-img" %>
      <h4 style="padding-top: 4rem; padding-left: 2rem;"><%= @group.title %></h4>
    </div>
  </div>
  <br><br>
    <%= link_to 'グループを削除', admin_group_path(@group), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %>

  <div class="py-4">
    <p><strong>説明</strong></p>
    <p><%= @group.description %></p>
  </div>

  <div id="message_count">
    <%= render 'admin/messages/count', messages: @messages %>
  </div>
  <div id="message_index">
    <%= render 'admin/messages/index', group: @group, message: @message %>
  </div>
</div>

<script>

  var toggleBtn = document.querySelector('.sidebar-toggle');
  var sidebar = document.querySelector('.sidebar');

  toggleBtn.addEventListener('click', function() {
    toggleBtn.classList.toggle('is-closed');
    sidebar.classList.toggle('is-closed');
  });
</script>