config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root :to =>"homes#top"
    get '/about' => 'homes#about'
    get "/mypage" => "users#mypage"
    resources :users, except: [:new, :index, :create] do
      collection do
        patch :withdraw
        get :check
      end
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resources :group_users, only: [:show, :create, :destroy]
      resources :group_characters
      resources :messages, only: [:create, :destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :rooms, only: [:create, :index, :show] do
      resources :direct_messages, only: [:create, :destroy]
    end
    # mount ActionCable.server => '/cable'
    resources :characters
    resources :schedules, except: [:index]
    resources :notifications, only: [:update]
    get "/search", to: "searches#search"
  end

  devise_scope :user do
    get '/users/sign_out', to: 'public/sessions#destroy'
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    # resources :groups, only: [:show, :index, :destroy]
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_user, only: [:destroy]
      resources :group_characters, only: [:show, :destroy]
      resources :messages, only: [:destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    resources :characters, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    get "/search", to: "searches#search"
  end

  devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :characters,      dependent: :destroy
  has_many :group_users,     dependent: :destroy
  has_many :permits,         dependent: :destroy
  has_many :groups,          through: :group_users
  has_many :messages,        dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
  has_many :rooms,           through: :entries
  has_many :notifications, dependent: :destroy

  has_one_attached :image

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :name, presence: true

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :profile, :description, :image, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/permits_helper.rb
module User::PermitsHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4 class="my-5"><%= @user.name %>さんの情報編集</h4>
    <%= form_with model: @user,url: admin_user_path(@user) do |f| %>
      <table class="table table-borderless">

        <tr>
          <td>ユーザーID</td>
          <td><%= @user.id %></td>
        </tr>

        <tr>
          <td>ユーザー名</td>
          <td><%= f.text_field :name %></td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email %></td>
          <td></td>
        </tr>

        <tr>
          <td>ステータス</td>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", { value: :false }  %>

            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会済", { value: :true } %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </tr>

      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4>ユーザー一覧</h4>
      <br>
      <table class="table">
        <thead>
          <tr>
            <thead>
            <th>ユーザー名</th>
            <th width="60">ID</th>
            <th>メールアドレス</th>
            <th><br></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= link_to "詳細表示", admin_user_path(user), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h4><%= @user.name %>さんの詳細</h4>
      <div class="d-flex align-items-center">
        <table class="table table-borderless">
          <tr>
            <th>ユーザーID</td>
            <td><%= @user.id %></td>
          </tr>
          <tr>

          <tr>
            <th>メールアドレス</th>
            <td><%= @user.email %></td>
          </tr>

          <tr>
            <th>会員ステータス</th>
            <th><%= @user.user_status %></th>
          </tr>

          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_user_path, class:"btn btn-success" %>

          </tr>
        </table>
      </div>
    </div>
  </div>
</div>