config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    post "/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root :to =>"homes#top"
    get '/about' => 'homes#about'
    get "/mypage" => "users#mypage"
    resources :users, except: [:new, :index, :create] do
      collection do
        patch :withdraw
        get :check
      end
    end
    resources :groups do
      resource :permits, only: [:create, :destroy]
      resources :group_users, only: [:show, :create, :destroy]
      resources :group_characters
      resources :messages, only: [:create, :destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    get "groups/:id/permits" => "groups#permits", as: :permits
    resources :rooms, only: [:create, :index, :show] do
      resources :direct_messages, only: [:create, :destroy]
    end
    # mount ActionCable.server => '/cable'
    resources :characters
    resources :schedules, except: [:index]
    resources :notifications, only: [:update]
    get "/search", to: "searches#search"
  end

  devise_scope :user do
    get '/users/sign_out', to: 'public/sessions#destroy'
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :users, only: [:index, :show, :edit, :update]
    # resources :groups, only: [:show, :index, :destroy]
    resources :groups, only: [:index, :show, :destroy] do
      resource :group_user, only: [:destroy]
      resources :group_characters, only: [:show, :destroy]
      resources :messages, only: [:destroy]
      collection do
        get 'play_character/:id', action: :play_character, as: 'play_character_with_id'
      end
    end
    resources :characters, only: [:index, :show, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    get "/search", to: "searches#search"
  end

  devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :group_characters
  has_many :groups,                      through: :group_characters
  belongs_to :user
  belongs_to :genre
  has_many :others,                      dependent: :destroy
  accepts_nested_attributes_for :others, allow_destroy: true

  has_one_attached :image
  validates :name, presence: true
  validates :status, presence: true
  validates :genre, presence: true


  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def initial_sanity
    (total3 || 0) * 5
  end

  def idea
    (total7 || 0) * 5
  end

  def knowledge
    (total8 || 0) * 5
  end

  def db_result
    total1 = (self.total1 || 0)
    total6 = (self.total6 || 0)
    db_total = total1 + total6

    if db_total >= 2 && db_total <= 12
      '-1D6'
    elsif db_total >= 13 && db_total <= 16
      '-1D4'
    elsif db_total >= 17 && db_total <= 24
      '+0'
    elsif db_total >= 25 && db_total <= 32
      '+1D4'
    elsif db_total >= 33 && db_total <= 40
      '+1D6'
    else
      '+1D6'
    end
  end

# 検索方法分岐
  def self.looks(search, word)
    if search == "partial"
      @character = Character.where("name LIKE?","%#{word}%")
    end
  end
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :content, presence: true, length: { maximum: 300 }
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :characters

  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users,      dependent: :destroy
  has_many :permits,          dependent: :destroy
  has_many :users,            through: :group_users, source: :user
  has_many :messages,         dependent: :destroy
  has_many :group_characters, dependent: :destroy
  has_many :characters,       through: :group_characters
  has_many :schedules
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  has_one_attached :image

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "partial"
      return Group.where("title LIKE ?", "%#{word}%")
    end
  end
end

app/models/group_character.rb
class GroupCharacter < ApplicationRecord
  belongs_to :character
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :content, presence: true, length: { maximum: 300 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true

end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :character

end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
  has_many :users,           through: :entries
  has_many :notifications, as: :notifiable, dependent: :destroy

end

app/models/rooms_helper.rb
module RoomsHelper

  # 最新メッセージのデータを取得して表示するメソッド
  def most_new_direct_message_preview(room)
    # 最新メッセージのデータを取得する
    direct_message = room.direct_messages.order(updated_at: :desc).limit(1)
    # 配列から取り出す
    direct_message = direct_message[0]
    # メッセージの有無を判定
    if direct_message.present?
      # メッセージがあれば内容を表示
      tag.p "#{direct_message.text}", class: "dm_list__content__link__box__direct_message"
    else
      # メッセージがなければ[ まだメッセージはありません ]を表示
      tag.p "[ まだメッセージはありません ]", class: "dm_list__content__link__box__direct_message"
    end
  end

  # 相手ユーザー名を取得して表示するメソッド
  def opponent_user(room)
    # 中間テーブルから相手ユーザーのデータを取得
    entry = room.entries.where.not(user_id: current_user)
    # 相手ユーザーの名前を取得
    name = entry[0].user.name
    # 名前を表示
    tag.p "#{name}", class: "dm_list__content__link__box__name"
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :characters,      dependent: :destroy
  has_many :group_users,     dependent: :destroy
  has_many :permits,         dependent: :destroy
  has_many :groups,          through: :group_users
  has_many :messages,        dependent: :destroy
  has_many :direct_messages, dependent: :destroy
  has_many :entries,         dependent: :destroy
  has_many :rooms,           through: :entries
  has_many :notifications, dependent: :destroy

  has_one_attached :image

  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :name, presence: true

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="position: bottom: 0; width: 100%;">
  <div class="footer">
    <div class="d-flex justify-content-center align-items-center">
    <ul>
      <div><%= image_tag asset_path('Saicolone.png'), size: '160x60', id: 'page-top' %></div>
        会社情報
        |
        サイトマップ
        |
        プライバシーポリシー
    </ul>
    </div>
  </div>
</footer>

<script>
$('#page-top').click(function () {
    $('body,html').animate({
        scrollTop: 0//ページトップまでスクロール
    }, 500);//ページトップスクロールの速さ。数字が大きいほど遅くなる
    return false;//リンク自体の無効化
});
</script>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="padding: 16px 16px 16px 0px; margin: 0px;">
    <div class="header container-fluid" style="padding-left: 0px;">
      <div class="box1"><%= link_to root_path, class: 'nav-link' do %>
        <%= image_tag asset_path('Saicolone.png'), size: '160x60' %></div>
      <% end %>

      <!-- ハンバーガーメニュー -->
      <div class="openbtn navbar-toggler ml-auto" data-toggle="collapse" data-target=".navbar-collapse" onclick="document.querySelector('.openbtn').classList.toggle('active')">
        <span></span>
        <span></span>
        <span></span>
      </div>

      <div class="collapse navbar-collapse justify-content-around" style="z-index: 998;">
        <ul class="navbar-nav" style="padding-bottom: 10px; padding-top: 6px;">

          <!--ユーザーログイン時-->
          <% if user_signed_in? %>
            <li><div class="header-content"><%= link_to "マイページ", mypage_path %></div></li>
            <li><div class="header-content"><%= link_to "キャラクター", characters_path %></div></li>
            <li><div class="header-content"><%= link_to "グループ", groups_path %></div></li>
            <li><div class="header-content"><%= link_to "DM", rooms_path %></div></li>
            <li><div class="header-content"><%= link_to "ログアウト", destroy_user_session_path %></div></li>

          <!--管理者ログイン時-->
          <% elsif admin_signed_in? %>
            <li><div class="header-content"><%= link_to "ユーザー一覧", admin_users_path %></div></li>
            <li><div class="header-content"><%= link_to "グループ一覧", admin_groups_path %></div></li>
            <li><div class="header-content"><%= link_to "キャラクター一覧", admin_characters_path %></div></li>
            <li><div class="header-content"><%= link_to "ジャンル作成", admin_genres_path %></div></li>
            <li><div class="header-content"><%= link_to "ログアウト", destroy_admin_session_path %></div></li>

          <% else %>

            <!--ログイン前-->
            <li><div class="header-content"><%= link_to "About", about_path %></div></li>
            <li><div class="header-content"><%= link_to "新規登録", new_user_registration_path %></div></li>
            <li><div class="header-content"><%= link_to "ログイン", new_user_session_path %></div></li>
          <% end %>

            <li class="nav-item" style="padding-top: 12px;">
              <div class="search_form">
                <%= form_with url: search_path, local: true, method: :get, class: "d-flex" do |f| %>
                  <%= f.text_field :word, class: "form-control me-2", placeholder: "グループ検索" %>
                  <%= f.hidden_field :range, value: "グループ" %> <!-- グループしか検索できないように設定 -->
                  <%= f.hidden_field :search, value: "partial" %> <!-- 部分一致しかできないように設定 -->
                  <button class="sbtn2" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                <% end %>
              </div>
            </li>
          </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saicolone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <script src="https://kit.fontawesome.com/1fccbc9d58.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
      <main class="mb-auto">
        <% if flash[:notice] %>
         <div class="alert alert-success" role="alert">
         <p class="notice text-center" style="color:green; margin-bottom: 0px;"><%= flash[:notice] %></p></div>
        <% end %>
        <% if flash[:alert] %>
         <div class="alert alert-danger" role="alert">
         <p class="alert text-center" style="color:red; margin-bottom: 0px;"><%= flash[:alert] %></p></div>
        <% end %>
        <%= yield %>
      </main>
    <%#= render 'layouts/footer' %>
  </body>
</html>